name: Generate Matrix
description: GitHub Action to create a dynamic Silverstripe CI matrix
inputs:
  # extra jobs must be multi-line string, as there's no support for type: array for inputs
  extra_jobs:
    type: string
    required: false
    default: ''
  composer_require_extra:
    type: string
    required: false
    default: ''
  # simple matrix will only run a single php 7.4 mysql 5.7 job instead of a full matrix
  simple_matrix:
    type: boolean
    default: false
  run_endtoend:
    type: boolean
    default: true
  run_phpcoverage:
    type: boolean
    # modules on silverstripe account will ignore this and always run codecov
    default: false
  run_phplinting:
    type: boolean
    default: true
  run_phpunit:
    type: boolean
    default: true
  run_js:
    type: boolean
    default: true
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
outputs:
  matrix:
    description: JSON matrix
    value: ${{ steps.php-script.outputs.matrix }}
runs:
  using: composite
  steps:  
    # TODO: confirm this actually does checkout the pull-request code in this context, or if instead if checkouts the action code
    - name: Checkout code
      uses: actions/checkout@v2
    # TODO: pin deps to shas
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: yaml
    - name: Create __inputs.yml
      shell: bash
      run: |
        if [ -f __inputs.yml ]; then rm __inputs.yml; fi
        touch __inputs.yml
        echo "run_endtoend: ${{ inputs.run_endtoend }}" >> __inputs.yml
        echo "run_js: ${{ inputs.run_js }}" >> __inputs.yml
        echo "run_phpcoverage: ${{ inputs.run_phpcoverage }}" >> __inputs.yml
        echo "run_phplinting: ${{ inputs.run_phplinting }}" >> __inputs.yml
        echo "run_phpunit: ${{ inputs.run_phpunit }}" >> __inputs.yml
        echo "simple_matrix: ${{ inputs.simple_matrix }}" >> __inputs.yml
        # this line may need to be hardened
        echo "github_repository: ${{ github.repository }}" >> __inputs.yml
        if [[ "${{ inputs.extra_jobs }}" != "" ]]; then echo "extra_jobs:" >> __inputs.yml; fi
        if [[ "${{ inputs.extra_jobs }}" != "" ]]; then echo "${{ inputs.extra_jobs }}" >> __inputs.yml; fi
        echo "cat __inputs.yml"
        cat __inputs.yml
    - name: debug
      shell: bash
      run: |
        echo "ls ."
        ls .
        echo "github.actions_path: ${{ github.action_path }}"
        echo "ls ${{ github.action_path }}"
        ls ${{ github.action_path }}
    - name: Run php script
      id: php-script
      shell: bash
      run: |
        MATRIX_JSON=$(php ${{ github.action_path }}/__script.php)
        echo "MATRIX_JSON: $MATRIX_JSON"
        echo "::set-output name=matrix::${MATRIX_JSON}"
